Support string literals
AeneasVerif/charon pull request #171
Opened 2024-05-06 08:44 UTC by Nadrieril

Fixes #72

2024-05-06 08:45 UTC, Nadrieril commented on charon-ml/src/NameMatcher.ml
> +  | LByteStr bs -> "[" ^ (String.concat ", " (List.map string_of_int bs)) ^ "]"
Is this corret? What is this printing used for?

2024-05-06 08:45 UTC, Nadrieril commented on charon-ml/src/PrintValues.ml
> +  | VByteStr bs -> "[" ^ (String.concat ", " (List.map string_of_int bs)) ^ "]"
There seems to be the same function defined twice; can we reuse one of them?

2024-05-06 08:48 UTC, Nadrieril commented on charon-ml/src/NameMatcher.ml
> +  | LByteStr bs -> "[" ^ String.concat ", " (List.map string_of_int bs) ^ "]"
There seems to be the same function defined twice; can we reuse one of them?

2024-05-06 09:20 UTC, Nadrieril commented
The problem with this is that aeneas does not have a pretty error path where it uses `Literal`, so to update aeneas I have to either ilplement it correctly for all backends or panic.

2024-05-13 12:42 UTC, sonmarcho commented on charon-ml/src/PrintValues.ml
> +  | VByteStr bs -> "[" ^ String.concat ", " (List.map string_of_int bs) ^ "]"
This is a "regular" pretty printing function used to pretty print the (U)LLBC ast. This looks good to me.

2024-05-13 12:50 UTC, sonmarcho requested changes

2024-05-13 13:10 UTC, Nadrieril commented on charon-ml/name_matcher_parser/Ast.ml
> +  | LByteStr of int list
What's a "pattern"?

2024-05-13 13:14 UTC, Nadrieril commented on charon/tests/ui/unsupported/plain-panic-str.out
> +thread 'rustc' panicked at 'Expected a next block after the call to core::panicking::panic_fmt.
So we ignore the argument to `panic!()`?

2024-05-14 11:33 UTC, sonmarcho approved these changes
Looks good now, thanks!

2024-05-14 14:01 UTC, merged