Added Error to RawStatement
AeneasVerif/charon pull request #208
Opened 2024-05-29 09:39 UTC by EschericHya

2024-05-29 09:50 UTC, Nadrieril commented on charon/src/pretty/fmt_with_ctx.rs
> +            RawStatement::Error => format!("{tab}panic"),
`Error` isn't a runtime panic in the emitted code, it's a compile-time error in Charon. I think we can indicate that like:
```suggestion
            RawStatement::Error => format!("{tab}/* charon error */"),
```

2024-05-29 14:39 UTC, Nadrieril commented
Looks good, we just need a test now. @sonmarcho what kind of error should we use this for?

2024-05-30 10:03 UTC, sonmarcho commented
> Looks good, we just need a test now. @sonmarcho what kind of error should we use this for?

If you look carefully we do not actually introduce the `Error` kind anywhere at this point, so we can't test it: we need to update the translation from Hax to ULLBC first. However, it might break some micro-passes (not sure, though) so I suggest doing that in a subsequent PR where we will add tests. For the missing features, anything will do and if you need inspiration just look at the `translate_statement` function (we can use intrinsics, some unsafe features, async/await, yield, etc. - I leave it to you guys :) ).

2024-05-30 10:04 UTC, sonmarcho commented
On a different topic: the CI failure is bizarre, right?

2024-05-30 10:06 UTC, sonmarcho requested changes

2024-05-30 10:06 UTC, sonmarcho commented on charon/src/ast/llbc_ast.rs
> +    Error,
I suggest adding a string with the unsupported statement: it can be useful for debugging (Lucas does this a lot in hax for instance).

2024-05-30 11:32 UTC, Nadrieril commented
> On a different topic: the CI failure is bizarre, right?

It happens because we changed the `Cargo.toml`, which updates `Cargo.lock` on the next run of `cargo`, but the `Cargo.lock` was not commited.

2024-05-30 11:34 UTC, EschericHya commented
I will commit it with the change suggested by @sonmarcho

2024-05-30 12:00 UTC, EschericHya commented
Raw_statement_to_json and charon-ml related changes still need to be propagated

2024-05-31 20:32 UTC, sonmarcho requested changes

2024-05-31 20:32 UTC, sonmarcho commented on charon-ml/src/LlbcAstUtils.ml
> +  | Break _ | Continue _ | Panic | Return | Error _ ->
Move the `Error` case with `SetDiscriminant`, `Assert`, etc.

2024-05-31 20:32 UTC, sonmarcho commented on charon-ml/src/PrintLlbcAst.ml
> +    | Error s -> indent ^ "error " ^ s
```suggestion
    | Error s -> indent ^ "ERROR(' " ^ s ^"')"
```

2024-05-31 20:32 UTC, sonmarcho commented on charon/src/pretty/fmt_with_ctx.rs
> +                format!("@Error{}", s)
```suggestion
                format!("@ERROR({})", s)
```

2024-05-31 20:32 UTC, sonmarcho commented on charon/src/pretty/fmt_with_ctx.rs
> +            RawStatement::Error(s) => format!("{tab}{}", s),
```suggestion
            RawStatement::Error(s) => format!("{tab}@ERROR({})", s),
```

2024-06-03 09:02 UTC, sonmarcho approved these changes
Looks good, thanks!

2024-06-04 13:13 UTC, merged

2024-06-04 13:32 UTC, Nadrieril commented
@msprotz this adds a new variant, eurydice will need to be updated

2024-06-04 13:32 UTC, Nadrieril commented
once again foiled by the lazy CI, I forgot to ping you beforehand sorry